name: Build and Release
permissions:
  contents: write
  discussions: write
on:
  push:
    branches:
      - master
      - dev
    tags:
      - "*"

jobs:
  build_and_release:
    runs-on: windows-latest
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
          - i686-pc-windows-msvc

    steps:
      - uses: actions/checkout@v2

      - name: Get binary name
        id: get_binary_name
        shell: pwsh
        run: |
          $metadata = cargo metadata --format-version 1 --no-deps | ConvertFrom-Json
          $binary_name = $metadata.packages[0].targets[0].name
          echo "binary_name=$binary_name" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Build
        shell: pwsh
        run: |
          cargo build --release --target ${{ matrix.target }}
          $binary_path = "target/${{ matrix.target }}/release/$env:binary_name.exe"
          Compress-Archive -Path $binary_path, bindings.ini -DestinationPath diakritika-${{ matrix.target }}.zip

      - name: Create release and upload assets
        if:  ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            diakritika-x86_64-pc-windows-msvc.zip
            diakritika-i686-pc-windows-msvc.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
