name: Build and Release

on:
  push:
    branches:
      - master
      - dev

jobs:
  build_and_release:
    runs-on: windows-latest
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
          - i686-pc-windows-msvc

    steps:
      - uses: actions/checkout@v2

      - name: Get binary name
        id: get_binary_name
        shell: pwsh
        run: |
          $metadata = cargo metadata --format-version 1 --no-deps | ConvertFrom-Json
          $binary_name = $metadata.packages[0].targets[0].name
          echo "binary_name=$binary_name" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Build
        shell: pwsh
        run: |
          cargo build --release --target ${{ matrix.target }}
          $binary_path = "target/${{ matrix.target }}/release/$env:binary_name.exe"
          Compress-Archive -Path $binary_path, your-ini-file.ini -DestinationPath release-${{ matrix.target }}.zip

      - name: Create Release and Upload x86_64 Asset
        if: matrix.target == 'x86_64-pc-windows-msvc'
        uses: softprops/action-gh-release@v1
        with:
          files: release-x86_64-pc-windows-msvc.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload i686 Asset to Release
        if: matrix.target == 'i686-pc-windows-msvc'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.build_and_release.outputs.upload_url }}
          asset_path: ./release-i686-pc-windows-msvc.zip
          asset_name: release-i686-pc-windows-msvc.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
